problem = GraphProblem(8, forbid_induced=(7,0), density=(3,3), minimize=True, type_orders=[6])
construction = GraphBlowupConstruction("6:112233445566", phantom_edge=(1,2))
problem.set_extremal_construction(construction)
problem.solve_sdp(True)
#problem.make_exact()