P = GraphProblem()
P.forbid_subgraph((3, 3))
P.n = 5
P.set_density("5:1223344551")
C = BlowupConstruction(GraphFlag("5:1223344551"))
P.set_extremal_construction(C)
P.compute_products()
P.solve_sdp()
P.change_solution_bases()
P.make_exact()
P.check_exact_bound()