problem = ThreeGraphAxiomsProblem(6, forbid=(4,4))
problem.clear_densities()
problem.add_degree_axiom(56165/100000, False)
problem.add_equal_degrees_axiom(True)
problem.solve_sdp(True)
problem.make_exact(2^20)