P = OrientedGraphProblem(3, density="3:1213")
x = polygen(QQ)
K = NumberField(x^2+x-1/2, 'x', embedding=0.366)
x=K.gen()
P.set_extremal_construction(field=K, target_bound=4*x - 1)
P.add_zero_eigenvectors(0, matrix(K, [[1 - x, 0, x], [x * (1 - x), 1 - x, x^2]]))
P.add_sharp_graphs(0, 2, 4, 5)
P.solve_sdp()
P.make_exact()