problem = OrientedGraphProblem(3, density="3:1213")
x = polygen(QQ)
K.<x> = NumberField(x^2 + x - 1/2, embedding=0.366)
problem.set_extremal_construction(field=K, target_bound=4*x - 1)
problem.add_zero_eigenvectors(0, matrix(K, [[1 - x, 0, x], [x * (1 - x), 1 - x, x^2]]))
problem.add_sharp_graphs(0, 2, 4, 5)
problem.solve_sdp()
problem.make_exact()